# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IVb0qCieSiet4WPoX5aZKqaA27Z2ClHI
"""

def main(user_input):
  userinput = "stuff"
  from model import model
  from nltk.tokenize import sent_tokenize
  from get_article_encodings import get_article_encodings
  from cluster_article_encodings import cluster_article_encodings
  from get_url import get_url
  from news_summarizer import news_summarizer
  #from plot_clusters import plot_clusters

  url = get_url(user_input)
  article = news_summarizer(url)
  article_sentences= sent_tokenize(article)

  article_sentences
  encoding_model, encoding_tokenizer = model()
  article_encodings = get_article_encodings(article_sentences, encoding_tokenizer, encoding_model)
  kmeans, ymeans, summary = cluster_article_encodings(article_sentences, article_encodings, n=3)

  # Will maybe do something with the neat cluster plot later once we get this all working

  return summary