# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I2NxGKqEz1WDy8qEwFKqKa5mH0xNwl7w
"""

def model():

    import torch
    from pytorch_transformers import XLNetConfig, XLNetTokenizer, XLNetModel

    #XLNetModel
    encoding_tokenizer = XLNetTokenizer.from_pretrained('xlnet-large-cased')
    encoding_model = XLNetModel.from_pretrained('xlnet-large-cased')
    encoding_model.eval()

    return encoding_model, encoding_tokenizer