# -*- coding: utf-8 -*-
"""plot_clusters.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/104Br7e-41aJavmAC_Dp97z4e041LOsD_
"""

#Function plot_clusters - plots the clusters
def plot_clusters(article_encodings, kmeans, y_kmeans):
  #KMeans clustering
  from sklearn.cluster import KMeans
  from sklearn.metrics import pairwise_distances_argmin_min

  #Sentence tokenization
  import nltk
  from nltk.tokenize import sent_tokenize
  nltk.download('punkt')

  from tqdm import tqdm, trange
  import pandas as pd
  import io
  import numpy as np
  import matplotlib.pyplot as plt

  plt.scatter(article_encodings[:, 0], article_encodings[:, 1], c=y_kmeans, s=50, cmap='viridis')
  centers = kmeans.cluster_centers_
  plot = plt.scatter(centers[:, 0], centers[:, 1], c='black', s=200, alpha=0.5);
  return plot